version: 2

run:
  timeout: 5m
  go: "1.24"

formatters:
  enable:
    - gofmt
    - goimports

linters:
  enable:
    # Default/recommended linters for Go projects
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    # Additional useful linters
    - gocyclo
    - misspell
    - revive
    - bodyclose
    # Code quality linters
    - gosec
    - unconvert
    - gocognit
    - prealloc
  settings:
    govet:
      enable:
        - shadow
    gocyclo:
      min-complexity: 15
    misspell:
      locale: US
    revive:
      min-confidence: 0.8
    lll:
      line-length: 120

issues:
  exclude-use-default: false
  exclude:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
